Code - OSS (1.64.2, kasan.kl.dfki.de:52192, desktop)
Jupyter Extension Version: 2022.3.1000752054.
Python Extension Version: 2022.4.1.
Info 10:37:17: ZMQ install verified.
Error 10:37:17: Jupyter Extension (Error in Failed to update settings.json, method:fixSettingsFile): [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://kasan.kl.dfki.de:52192/root/.config/Code/User/settings.json' (Error: Unable to resolve nonexistent file 'vscode-remote://kasan.kl.dfki.de:52192/root/.config/Code/User/settings.json')
	at Function._handleError (/tmp/code-server-4.2.0-linux-amd64/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:83879)
	at Object.readFile (/tmp/code-server-4.2.0-linux-amd64/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:82793)
	at async m.readFile (/home/kadir/IML/Quantus/.code-server/extensions/ms-toolsai.jupyter-2022.3.1000752054/out/client/extension.js:2:118743)
	at async g.fixSettingsFile (/home/kadir/IML/Quantus/.code-server/extensions/ms-toolsai.jupyter-2022.3.1000752054/out/client/extension.js:2:4943)
	at async Promise.all (index 0)
	at async g.updateSettings (/home/kadir/IML/Quantus/.code-server/extensions/ms-toolsai.jupyter-2022.3.1000752054/out/client/extension.js:2:6705)] {
  code: 'FileNotFound'
}
Error 10:37:17: Jupyter Extension (Error in Failed to update settings.json, method:fixSettingsFile): [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://kasan.kl.dfki.de:52192/home/kadir/IML/Quantus/.vscode/settings.json' (Error: Unable to resolve nonexistent file 'vscode-remote://kasan.kl.dfki.de:52192/home/kadir/IML/Quantus/.vscode/settings.json')
	at Function._handleError (/tmp/code-server-4.2.0-linux-amd64/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:83879)
	at Object.readFile (/tmp/code-server-4.2.0-linux-amd64/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:82793)
	at async m.readFile (/home/kadir/IML/Quantus/.code-server/extensions/ms-toolsai.jupyter-2022.3.1000752054/out/client/extension.js:2:118743)
	at async g.fixSettingsFile (/home/kadir/IML/Quantus/.code-server/extensions/ms-toolsai.jupyter-2022.3.1000752054/out/client/extension.js:2:4943)
	at async Promise.all (index 1)
	at async g.updateSettings (/home/kadir/IML/Quantus/.code-server/extensions/ms-toolsai.jupyter-2022.3.1000752054/out/client/extension.js:2:6705)] {
  code: 'FileNotFound'
}
Info 10:37:17: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 10:37:17: Getting activation commands for /usr/bin/python3 are not cached. May take a while.
Info 10:37:17: Process Execution: > /usr/bin/python3 -m pip list
> /usr/bin/python3 -m pip list
Info 10:37:17: Process Execution: > /usr/bin/python3 -c "import pip"
> /usr/bin/python3 -c "import pip"
Info 11:08:43: Process Execution: > /usr/bin/python3 -m pip list
> /usr/bin/python3 -m pip list
Info 11:08:43: Process Execution: > /usr/bin/python3 -c "import pip"
> /usr/bin/python3 -c "import pip"
Info 11:08:48: Getting activation commands for /opt/conda/bin/python are not cached. May take a while.
Info 11:08:48: Activation Commands received source /opt/conda/bin/activate,conda activate base for shell bash
Info 11:08:49: Process Execution: > /opt/conda/bin/python -m pip list
> /opt/conda/bin/python -m pip list
Info 11:17:38: Shutting down notebooks for 665894d7-3596-4469-b587-61a2e434e256
Info 11:17:38: Disposing HostJupyterExecution b593dde2-f3fd-4579-bb6f-9584d2677f5b
Info 11:17:38: Disposing super HostJupyterExecution b593dde2-f3fd-4579-bb6f-9584d2677f5b
Info 11:17:38: Disposing HostJupyterExecution b593dde2-f3fd-4579-bb6f-9584d2677f5b
Info 11:17:38: Finished disposing HostJupyterExecution  b593dde2-f3fd-4579-bb6f-9584d2677f5b
Info 11:17:38: Cleaning up server cache b593dde2-f3fd-4579-bb6f-9584d2677f5b
Info 11:17:38: Finished disposing HostJupyterExecution  b593dde2-f3fd-4579-bb6f-9584d2677f5b
